# -*- coding: utf-8 -*-
"""Malicious URL Detection System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nokm5F1yqwq8neME8VqV3-eVZJWOHwym
"""

import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import matplotlib.pyplot as plt

# LOAD DATA
df = pd.read_csv(
    "benign_vs_defacement_urls.csv",
    encoding="latin1",
    on_bad_lines="skip",
    engine="python"
)

df.columns = df.columns.str.strip().str.lower()

if "label" not in df.columns:
    df = df.rename(columns={"type": "label"})

# shuffle dataset
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# take subset
df = df.head(30000)

# CLEAN LABELS
df["label"] = df["label"].astype(str).str.strip().str.lower()

df["label"] = df["label"].replace({
    "benign": 0,
    "normal": 0,
    "good": 0,
    "defacement": 1,
    "malicious": 1,
    "bad": 1
})

df = df[df["label"].isin([0, 1])]
df["label"] = df["label"].astype(int)
print("Class distribution:\n", df["label"].value_counts())

# FEATURE ENGINEERING
df["url_len"] = df["url"].str.len()
df["dots"] = df["url"].str.count(r"\.")
df["digits"] = df["url"].str.count(r"\d")
df["slashes"] = df["url"].str.count("/")
df["has_ip"] = df["url"].str.contains(r"\d+\.\d+\.\d+\.\d+").astype(int)
df["short_url"] = df["url"].str.contains("bit.ly|tinyurl|goo.gl|t.co").astype(int)


# BALANCING FEATURES
min_count = df["label"].value_counts().min()

df_balanced = pd.concat([
    df[df["label"] == 0].sample(min_count, random_state=42),
    df[df["label"] == 1].sample(min_count, random_state=42)
])


# SPLITTING DATA
X = df_balanced[["url_len", "dots", "digits", "slashes", "has_ip", "short_url"]]
y = df_balanced["label"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


# MODELS
models = {
    "Logistic Regression": LogisticRegression(max_iter=500),
    "Linear SVM": LinearSVC(),
    "Decision Tree": DecisionTreeClassifier(max_depth=5)
}

# TRAINING MODEL
results = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    results[name] = acc

    print(f"\n===== {name} =====")
    print("Accuracy:", acc)
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))


# VISUALIZATION
plt.figure()
plt.bar(results.keys(), results.values())
plt.title("Model Accuracy Comparison")
plt.xticks(rotation=20)
plt.show()